version: "2"
linters:
  default: standard
  enable:
    - exhaustruct_v5
  settings:
    exhaustruct_v5:
      ignore-patterns:
        - '.+/cobra\.Command$'
        - '.+/http\.Client$'
        - '.+/url\.URL$'
        - '.+/tar\.Header$'
formatters:
  enable:
    - gofmt
    - goimports
    - gofumpt
