# https://taskfile.dev

version: "3"

env:
  VERSION: '{{.VERSION | default "0.0.0" }}'

vars:
  BINARY: ./build/urlscan
  LDFLAGS: -ldflags "-X github.com/urlscan/urlscan-cli/pkg/version.Version={{.VERSION}}"

tasks:
  update:
    cmds:
      - go get -u
  install:
    cmds:
      - go mod tidy
  build:
    cmds:
      - go build {{.LDFLAGS}} -o {{.BINARY}} ./main.go
  clean:
    cmds:
      - rm -rf ./build
      - rm -rf ./dist
